[project]
name = "transcriptex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "youtube-transcript-api>=1.2.3",
    "yt-dlp>=2025.12.8",
]
